#lang racket
(define (cube)
  (display "Вычисление объема куба.")(newline)
  (display "Введите длину ребра (см) и нажмите клавишу <Enter> = ")
  (define a (read))
  (display "Объем куба: ")
  (display (* a a a))
  (display " куб.см.")(newline))
(cube)
(newline)

(define (shopping)
  (display "Вычисление стоимости покупки.")(newline)
  (display "Введите исходные данные:")(newline)
  (display "Цена тетради (руб.) = ")
  (define ct (read))
  (display "Количество тетрадей = ")
  (define kt (read))
  (display "Цена карандаша (руб.) = ")
  (define ck (read))
  (display "Количество карандашей = ")
  (define kk (read))
  (display "Стоимость покупки: ")
  (display (+ (* ct kt) (* ck kk)))
  (display " руб.")(newline))
(shopping)
(newline)

(define (insert message)
  (display message)
  (read))

(define (Oms R1 R2)
  (display "Сопротивление цепи: ")
  (display (/ 1 (+ (/ 1 R1) (/ 1 R2))))
  (display " Ом")(newline))
(display "Вычисление сопротивления электрической цепи.")(newline)
(display "Введите исходные данные:")(newline)
(Oms (insert "Величина первого сопротивления (Ом) = ") (insert "Величина второго сопротивления (Ом) = "))

  
